
#include "analysis.h"

# include <iostream>
#include "TFile.h"
#include "TTree.h"
#include "TDirectoryFile.h"
#include "TH1D.h"
#include "TH1F.h"
#include "TH1I.h"

using namespace std;
int main(int argc, char **argv){
//Declaration of leaves types
   Double_t        eta;
   Double_t        costhetalj;
   Double_t        costhetalbl;
   Double_t        costhetalj1;
   Double_t        costhetalbl1;
   Double_t        costhetalj2;
   Double_t        costhetalbl2;
   Double_t        Mlb1;
   Double_t        Mlb2;
   Double_t        b1b2Mass;
   Double_t        b1b2Pt;
   Double_t        mtwMass;
   Int_t           charge;
   Int_t           runid;
   Int_t           lumiid;
   Int_t           eventid;
   Double_t        weight;
   Double_t        totalWeight;
   Double_t        bWeight;
   Double_t        bWeightBTagUp;
   Double_t        bWeightBTagDown;
   Double_t        bWeightMisTagUp;
   Double_t        bWeightMisTagDown;
   Double_t        PUWeight;
   Double_t        PUWeightPUUp;
   Double_t        PUWeightPUDown;
   Double_t        topPtReweightMCTruth;
   Double_t        topPtReweight;
   Double_t        leptonPt;
   Double_t        leptonEta;
   Double_t        leptonPhi;
   Double_t        leptonDeltaCorrectedRelIso;
   Double_t        leptonRhoCorrectedRelIso;
   Double_t        leptonSF;
   Double_t        leptonSFB;
   Double_t        leptonSFC;
   Double_t        leptonSFD;
   Double_t        leptonSFIDUp;
   Double_t        leptonSFIDUpB;
   Double_t        leptonSFIDUpC;
   Double_t        leptonSFIDUpD;
   Double_t        leptonSFIDDown;
   Double_t        leptonSFIDDownB;
   Double_t        leptonSFIDDownC;
   Double_t        leptonSFIDDownD;
   Double_t        leptonSFIsoUp;
   Double_t        leptonSFIsoUpB;
   Double_t        leptonSFIsoUpC;
   Double_t        leptonSFIsoUpD;
   Double_t        leptonSFIsoDown;
   Double_t        leptonSFIsoDownB;
   Double_t        leptonSFIsoDownC;
   Double_t        leptonSFIsoDownD;
   Double_t        leptonSFTrigUp;
   Double_t        leptonSFTrigUpB;
   Double_t        leptonSFTrigUpC;
   Double_t        leptonSFTrigUpD;
   Double_t        leptonSFTrigDown;
   Double_t        leptonSFTrigDownB;
   Double_t        leptonSFTrigDownC;
   Double_t        leptonSFTrigDownD;
   Double_t        fJetPt;
   Double_t        fJetE;
   Double_t        fJetEta;
   Double_t        fJetPhi;
   Double_t        fJetBtag;
   Int_t           fJetFlavour;
   Double_t        fJetPUID;
   Double_t        fJetPUWP;
   Double_t        fJetBeta;
   Double_t        fJetDZ;
   Double_t        fJetRMS;
   Double_t        bJetBeta;
   Double_t        bJetDZ;
   Double_t        bJetRMS;
   Double_t        bJetPt;
   Double_t        bJetE;
   Double_t        bJetEta;
   Double_t        bJetPhi;
   Double_t        bJetBtag;
   Int_t           bJetFlavour;
   Double_t        bJetPUID;
   Double_t        bJetPUWP;
   Double_t        firstJetPt;
   Double_t        firstJetEta;
   Double_t        firstJetPhi;
   Double_t        firstJetE;
   Double_t        firstJetBtag;
   Int_t           firstJetFlavour;
   Double_t        secondJetPt;
   Double_t        secondJetEta;
   Double_t        secondJetPhi;
   Double_t        secondJetE;
   Double_t        secondJetBtag;
   Int_t           secondJetFlavour;
   Double_t        looseJetPt;
   Double_t        looseJetEta;
   Double_t        looseJetPhi;
   Double_t        looseJetE;
   Double_t        looseJetBtag;
   Int_t           looseJetFlavour;
   Double_t        bJet1Pt;
   Double_t        bJet1E;
   Double_t        bJet1Eta;
   Double_t        bJet1Phi;
   Double_t        bJet1Btag;
   Int_t           bJet1Flavour;
   Double_t        bJet2Pt;
   Double_t        bJet2E;
   Double_t        bJet2Eta;
   Double_t        bJet2Phi;
   Double_t        bJet2Btag;
   Int_t           bJet2Flavour;
   Int_t           nJLoose;
   Int_t           nJLooseCentral;
   Int_t           nJLooseForward;
   Int_t           nJLooseMBTag;
   Int_t           eventFlavour;
   Double_t        metPt;
   Double_t        metPhi;
   Double_t        HT;
   Double_t        H;
   Double_t        topMass;
   Double_t        top1Mass;
   Double_t        top2Mass;
   Double_t        topMtw;
   Double_t        topPt;
   Double_t        topPhi;
   Double_t        topEta;
   Double_t        topE;
   Double_t        top1Pt;
   Double_t        top1Phi;
   Double_t        top1Eta;
   Double_t        top1E;
   Double_t        top2Pt;
   Double_t        top2Phi;
   Double_t        top2Eta;
   Double_t        top2E;
   Int_t           ID;
   Double_t        MVAID;
   Int_t           nVertices;
   Int_t           nGoodVertices;
   Double_t        totalEnergy;
   Double_t        totalMomentum;
   Double_t        lowBTag;
   Double_t        highBTag;
   Float_t         MCTop_1_Pt;
   Float_t         MCTop_1_Phi;
   Float_t         MCTop_1_Eta;
   Float_t         MCTop_1_E;
   Float_t         MCTop_1_PdgId;
   Float_t         MCTop_1_MotherId;
   Float_t         MCTopLepton_1_Pt;
   Float_t         MCTopLepton_1_Phi;
   Float_t         MCTopLepton_1_Eta;
   Float_t         MCTopLepton_1_E;
   Float_t         MCTopLepton_1_PdgId;
   Float_t         MCTopLepton_1_MotherId;
   Float_t         MCTopNeutrino_1_Pt;
   Float_t         MCTopNeutrino_1_Phi;
   Float_t         MCTopNeutrino_1_Eta;
   Float_t         MCTopNeutrino_1_E;
   Float_t         MCTopNeutrino_1_PdgId;
   Float_t         MCTopNeutrino_1_MotherId;
   Float_t         MCTopQuark_1_Pt;
   Float_t         MCTopQuark_1_Phi;
   Float_t         MCTopQuark_1_Eta;
   Float_t         MCTopQuark_1_E;
   Float_t         MCTopQuark_1_PdgId;
   Float_t         MCTopQuark_1_MotherId;
   Float_t         MCTopQuarkBar_1_Pt;
   Float_t         MCTopQuarkBar_1_Phi;
   Float_t         MCTopQuarkBar_1_Eta;
   Float_t         MCTopQuarkBar_1_E;
   Float_t         MCTopQuarkBar_1_PdgId;
   Float_t         MCTopQuarkBar_1_MotherId;
   Float_t         MCTopBQuark_1_Pt;
   Float_t         MCTopBQuark_1_Phi;
   Float_t         MCTopBQuark_1_Eta;
   Float_t         MCTopBQuark_1_E;
   Float_t         MCTopBQuark_1_PdgId;
   Float_t         MCTopBQuark_1_MotherId;
   Float_t         MCTopW_1_Pt;
   Float_t         MCTopW_1_Phi;
   Float_t         MCTopW_1_Eta;
   Float_t         MCTopW_1_E;
   Float_t         MCTopW_1_PdgId;
   Float_t         MCTopW_1_DauOneId;
   Int_t           nMCTruthLeptons;
   Float_t         MCTop_2_Pt;
   Float_t         MCTop_2_Phi;
   Float_t         MCTop_2_Eta;
   Float_t         MCTop_2_E;
   Float_t         MCTop_2_PdgId;
   Float_t         MCTop_2_MotherId;
   Float_t         MCTopLepton_2_Pt;
   Float_t         MCTopLepton_2_Phi;
   Float_t         MCTopLepton_2_Eta;
   Float_t         MCTopLepton_2_E;
   Float_t         MCTopLepton_2_PdgId;
   Float_t         MCTopLepton_2_MotherId;
   Float_t         MCTopNeutrino_2_Pt;
   Float_t         MCTopNeutrino_2_Phi;
   Float_t         MCTopNeutrino_2_Eta;
   Float_t         MCTopNeutrino_2_E;
   Float_t         MCTopNeutrino_2_PdgId;
   Float_t         MCTopNeutrino_2_MotherId;
   Float_t         MCTopQuark_2_Pt;
   Float_t         MCTopQuark_2_Phi;
   Float_t         MCTopQuark_2_Eta;
   Float_t         MCTopQuark_2_E;
   Float_t         MCTopQuark_2_PdgId;
   Float_t         MCTopQuark_2_MotherId;
   Float_t         MCTopQuarkBar_2_Pt;
   Float_t         MCTopQuarkBar_2_Phi;
   Float_t         MCTopQuarkBar_2_Eta;
   Float_t         MCTopQuarkBar_2_E;
   Float_t         MCTopQuarkBar_2_PdgId;
   Float_t         MCTopQuarkBar_2_MotherId;
   Float_t         MCTopBQuark_2_Pt;
   Float_t         MCTopBQuark_2_Phi;
   Float_t         MCTopBQuark_2_Eta;
   Float_t         MCTopBQuark_2_E;
   Float_t         MCTopBQuark_2_PdgId;
   Float_t         MCTopBQuark_2_MotherId;
   Float_t         MCTopW_2_Pt;
   Float_t         MCTopW_2_Phi;
   Float_t         MCTopW_2_Eta;
   Float_t         MCTopW_2_E;
   Float_t         MCTopW_2_PdgId;
   Float_t         MCTopW_2_DauOneId;
   Float_t         MCQuark_1_Pt;
   Float_t         MCQuark_1_Phi;
   Float_t         MCQuark_1_Eta;
   Float_t         MCQuark_1_E;
   Float_t         MCQuark_1_PdgId;
   Float_t         MCQuark_1_MotherId;
   Float_t         MCQuark_2_Pt;
   Float_t         MCQuark_2_Phi;
   Float_t         MCQuark_2_Eta;
   Float_t         MCQuark_2_E;
   Float_t         MCQuark_2_PdgId;
   Float_t         MCQuark_2_MotherId;
   Float_t         MCQuark_3_Pt;
   Float_t         MCQuark_3_Phi;
   Float_t         MCQuark_3_Eta;
   Float_t         MCQuark_3_E;
   Float_t         MCQuark_3_PdgId;
   Float_t         MCQuark_3_MotherId;
   Float_t         MCQuark_4_Pt;
   Float_t         MCQuark_4_Phi;
   Float_t         MCQuark_4_Eta;
   Float_t         MCQuark_4_E;
   Float_t         MCQuark_4_PdgId;
   Float_t         MCQuark_4_MotherId;
   Float_t         MCQuark_5_Pt;
   Float_t         MCQuark_5_Phi;
   Float_t         MCQuark_5_Eta;
   Float_t         MCQuark_5_E;
   Float_t         MCQuark_5_PdgId;
   Float_t         MCQuark_5_MotherId;
   Float_t         MCQuark_6_Pt;
   Float_t         MCQuark_6_Phi;
   Float_t         MCQuark_6_Eta;
   Float_t         MCQuark_6_E;
   Float_t         MCQuark_6_PdgId;
   Float_t         MCQuark_6_MotherId;
   Float_t         MCQuark_7_Pt;
   Float_t         MCQuark_7_Phi;
   Float_t         MCQuark_7_Eta;
   Float_t         MCQuark_7_E;
   Float_t         MCQuark_7_PdgId;
   Float_t         MCQuark_7_MotherId;
   Float_t         MCQuark_8_Pt;
   Float_t         MCQuark_8_Phi;
   Float_t         MCQuark_8_Eta;
   Float_t         MCQuark_8_E;
   Float_t         MCQuark_8_PdgId;
   Float_t         MCQuark_8_MotherId;
   Float_t         MCQuark_9_Pt;
   Float_t         MCQuark_9_Phi;
   Float_t         MCQuark_9_Eta;
   Float_t         MCQuark_9_E;
   Float_t         MCQuark_9_PdgId;
   Float_t         MCQuark_9_MotherId;
   Float_t         MCQuark_10_Pt;
   Float_t         MCQuark_10_Phi;
   Float_t         MCQuark_10_Eta;
   Float_t         MCQuark_10_E;
   Float_t         MCQuark_10_PdgId;
   Float_t         MCQuark_10_MotherId;
   Float_t         MCQuark_11_Pt;
   Float_t         MCQuark_11_Phi;
   Float_t         MCQuark_11_Eta;
   Float_t         MCQuark_11_E;
   Float_t         MCQuark_11_PdgId;
   Float_t         MCQuark_11_MotherId;
   Float_t         MCQuark_12_Pt;
   Float_t         MCQuark_12_Phi;
   Float_t         MCQuark_12_Eta;
   Float_t         MCQuark_12_E;
   Float_t         MCQuark_12_PdgId;
   Float_t         MCQuark_12_MotherId;
   Float_t         MCBQuark_1_Pt;
   Float_t         MCBQuark_1_Phi;
   Float_t         MCBQuark_1_Eta;
   Float_t         MCBQuark_1_E;
   Float_t         MCBQuark_1_PdgId;
   Float_t         MCBQuark_1_MotherId;
   Float_t         MCLepton_1_Pt;
   Float_t         MCLepton_1_Phi;
   Float_t         MCLepton_1_Eta;
   Float_t         MCLepton_1_E;
   Float_t         MCLepton_1_PdgId;
   Float_t         MCLepton_1_MotherId;
   Float_t         MCNeutrino_1_Pt;
   Float_t         MCNeutrino_1_Phi;
   Float_t         MCNeutrino_1_Eta;
   Float_t         MCNeutrino_1_E;
   Float_t         MCNeutrino_1_PdgId;
   Float_t         MCNeutrino_1_MotherId;
   Float_t         MCBQuark_2_Pt;
   Float_t         MCBQuark_2_Phi;
   Float_t         MCBQuark_2_Eta;
   Float_t         MCBQuark_2_E;
   Float_t         MCBQuark_2_PdgId;
   Float_t         MCBQuark_2_MotherId;
   Float_t         MCLepton_2_Pt;
   Float_t         MCLepton_2_Phi;
   Float_t         MCLepton_2_Eta;
   Float_t         MCLepton_2_E;
   Float_t         MCLepton_2_PdgId;
   Float_t         MCLepton_2_MotherId;
   Float_t         MCNeutrino_2_Pt;
   Float_t         MCNeutrino_2_Phi;
   Float_t         MCNeutrino_2_Eta;
   Float_t         MCNeutrino_2_E;
   Float_t         MCNeutrino_2_PdgId;
   Float_t         MCNeutrino_2_MotherId;
   Float_t         MCBQuark_3_Pt;
   Float_t         MCBQuark_3_Phi;
   Float_t         MCBQuark_3_Eta;
   Float_t         MCBQuark_3_E;
   Float_t         MCBQuark_3_PdgId;
   Float_t         MCBQuark_3_MotherId;
   Float_t         MCLepton_3_Pt;
   Float_t         MCLepton_3_Phi;
   Float_t         MCLepton_3_Eta;
   Float_t         MCLepton_3_E;
   Float_t         MCLepton_3_PdgId;
   Float_t         MCLepton_3_MotherId;
   Float_t         MCNeutrino_3_Pt;
   Float_t         MCNeutrino_3_Phi;
   Float_t         MCNeutrino_3_Eta;
   Float_t         MCNeutrino_3_E;
   Float_t         MCNeutrino_3_PdgId;
   Float_t         MCNeutrino_3_MotherId;
   Float_t         MCBQuark_4_Pt;
   Float_t         MCBQuark_4_Phi;
   Float_t         MCBQuark_4_Eta;
   Float_t         MCBQuark_4_E;
   Float_t         MCBQuark_4_PdgId;
   Float_t         MCBQuark_4_MotherId;
   Float_t         MCLepton_4_Pt;
   Float_t         MCLepton_4_Phi;
   Float_t         MCLepton_4_Eta;
   Float_t         MCLepton_4_E;
   Float_t         MCLepton_4_PdgId;
   Float_t         MCLepton_4_MotherId;
   Float_t         MCNeutrino_4_Pt;
   Float_t         MCNeutrino_4_Phi;
   Float_t         MCNeutrino_4_Eta;
   Float_t         MCNeutrino_4_E;
   Float_t         MCNeutrino_4_PdgId;
   Float_t         MCNeutrino_4_MotherId;
   Float_t         PDFWeight1;
   Float_t         PDFWeight2;
   Float_t         PDFWeight3;
   Float_t         PDFWeight4;
   Float_t         PDFWeight5;
   Float_t         PDFWeight6;
   Float_t         PDFWeight7;
   Float_t         PDFWeight8;
   Float_t         PDFWeight9;
   Float_t         PDFWeight10;
   Float_t         PDFWeight11;
   Float_t         PDFWeight12;
   Float_t         PDFWeight13;
   Float_t         PDFWeight14;
   Float_t         PDFWeight15;
   Float_t         PDFWeight16;
   Float_t         PDFWeight17;
   Float_t         PDFWeight18;
   Float_t         PDFWeight19;
   Float_t         PDFWeight20;
   Float_t         PDFWeight21;
   Float_t         PDFWeight22;
   Float_t         PDFWeight23;
   Float_t         PDFWeight24;
   Float_t         PDFWeight25;
   Float_t         PDFWeight26;
   Float_t         PDFWeight27;
   Float_t         PDFWeight28;
   Float_t         PDFWeight29;
   Float_t         PDFWeight30;
   Float_t         PDFWeight31;
   Float_t         PDFWeight32;
   Float_t         PDFWeight33;
   Float_t         PDFWeight34;
   Float_t         PDFWeight35;
   Float_t         PDFWeight36;
   Float_t         PDFWeight37;
   Float_t         PDFWeight38;
   Float_t         PDFWeight39;
   Float_t         PDFWeight40;
   Float_t         PDFWeight41;
   Float_t         PDFWeight42;
   Float_t         PDFWeight43;
   Float_t         PDFWeight44;
   Float_t         PDFWeight45;
   Float_t         PDFWeight46;
   Float_t         PDFWeight47;
   Float_t         PDFWeight48;
   Float_t         PDFWeight49;
   Float_t         PDFWeight50;
   Float_t         PDFWeight51;
   Float_t         PDFWeight52;
   Float_t         PDFWeight_MSTW;
   Float_t         PDFWeight_NNPDF21;
   Float_t         PDFWeight_GJR_FV;
   Float_t         PDFWeight_GJR_FF;
   Float_t         PDFWeight_GJR_FDIS;
   Float_t         PDFWeight_HERAPDF;
   Double_t        topPtReweightMCTruthNorm;
   Double_t        topPtReweightNorm;
   Double_t        topPtReweightMCTruthNormUp;
   Double_t        topPtReweightNormUp;
   Double_t        topPtReweightMCTruthNormDown;
   Double_t        topPtReweightNormDown;
   
    TFile T("TChannel.root");
    TTree* TChannel_2J_1T_noSyst = (TTree*)T.Get("TreesEle/TChannel_2J_1T_noSyst");
    
    TFile E("TChannel-ele-histo.root","recreate");
    TH1D h_topMass("h_topMass","Top Mass; Mass (GeV); Events", 50, 100, 250);
    TH1D h_leptonPt("h_leptonPt","; PT(GeV); Events", 50, 0, 250);
    TH1D h_leptonEta("h_leptonEta","; eta; Events", 50, 0, 6);
    TH1D h_leptonPhi("h_leptonPhi","; phi; Events", 50, -3.14, 3.14);
    //TH1D h_("h_","; (GeV); Events", 50, 100, 250);
    TH1D h_fJetEta("h_fJetEta","f Jet eta; eta; Events", 50, 0, 6);
    TH1D h_bJetEta("h_bJetEta","title;x;y",50,0,6);

    // Set branch addresses.   
   {
        TChannel_2J_1T_noSyst->SetBranchAddress("eta",&eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("costhetalj",&costhetalj);
        TChannel_2J_1T_noSyst->SetBranchAddress("costhetalbl",&costhetalbl);
        TChannel_2J_1T_noSyst->SetBranchAddress("costhetalj1",&costhetalj1);
        TChannel_2J_1T_noSyst->SetBranchAddress("costhetalbl1",&costhetalbl1);
        TChannel_2J_1T_noSyst->SetBranchAddress("costhetalj2",&costhetalj2);
        TChannel_2J_1T_noSyst->SetBranchAddress("costhetalbl2",&costhetalbl2);
        TChannel_2J_1T_noSyst->SetBranchAddress("Mlb1",&Mlb1);
        TChannel_2J_1T_noSyst->SetBranchAddress("Mlb2",&Mlb2);
        TChannel_2J_1T_noSyst->SetBranchAddress("b1b2Mass",&b1b2Mass);
        TChannel_2J_1T_noSyst->SetBranchAddress("b1b2Pt",&b1b2Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("mtwMass",&mtwMass);
        TChannel_2J_1T_noSyst->SetBranchAddress("charge",&charge);
        TChannel_2J_1T_noSyst->SetBranchAddress("runid",&runid);
        TChannel_2J_1T_noSyst->SetBranchAddress("lumiid",&lumiid);
        TChannel_2J_1T_noSyst->SetBranchAddress("eventid",&eventid);
        TChannel_2J_1T_noSyst->SetBranchAddress("weight",&weight);
        TChannel_2J_1T_noSyst->SetBranchAddress("totalWeight",&totalWeight);
        TChannel_2J_1T_noSyst->SetBranchAddress("bWeight",&bWeight);
        TChannel_2J_1T_noSyst->SetBranchAddress("bWeightBTagUp",&bWeightBTagUp);
        TChannel_2J_1T_noSyst->SetBranchAddress("bWeightBTagDown",&bWeightBTagDown);
        TChannel_2J_1T_noSyst->SetBranchAddress("bWeightMisTagUp",&bWeightMisTagUp);
        TChannel_2J_1T_noSyst->SetBranchAddress("bWeightMisTagDown",&bWeightMisTagDown);
        TChannel_2J_1T_noSyst->SetBranchAddress("PUWeight",&PUWeight);
        TChannel_2J_1T_noSyst->SetBranchAddress("PUWeightPUUp",&PUWeightPUUp);
        TChannel_2J_1T_noSyst->SetBranchAddress("PUWeightPUDown",&PUWeightPUDown);
        TChannel_2J_1T_noSyst->SetBranchAddress("topPtReweightMCTruth",&topPtReweightMCTruth);
        TChannel_2J_1T_noSyst->SetBranchAddress("topPtReweight",&topPtReweight);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonPt",&leptonPt);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonEta",&leptonEta);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonPhi",&leptonPhi);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonDeltaCorrectedRelIso",&leptonDeltaCorrectedRelIso);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonRhoCorrectedRelIso",&leptonRhoCorrectedRelIso);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSF",&leptonSF);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFB",&leptonSFB);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFC",&leptonSFC);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFD",&leptonSFD);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFIDUp",&leptonSFIDUp);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFIDUpB",&leptonSFIDUpB);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFIDUpC",&leptonSFIDUpC);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFIDUpD",&leptonSFIDUpD);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFIDDown",&leptonSFIDDown);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFIDDownB",&leptonSFIDDownB);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFIDDownC",&leptonSFIDDownC);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFIDDownD",&leptonSFIDDownD);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFIsoUp",&leptonSFIsoUp);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFIsoUpB",&leptonSFIsoUpB);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFIsoUpC",&leptonSFIsoUpC);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFIsoUpD",&leptonSFIsoUpD);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFIsoDown",&leptonSFIsoDown);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFIsoDownB",&leptonSFIsoDownB);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFIsoDownC",&leptonSFIsoDownC);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFIsoDownD",&leptonSFIsoDownD);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFTrigUp",&leptonSFTrigUp);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFTrigUpB",&leptonSFTrigUpB);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFTrigUpC",&leptonSFTrigUpC);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFTrigUpD",&leptonSFTrigUpD);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFTrigDown",&leptonSFTrigDown);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFTrigDownB",&leptonSFTrigDownB);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFTrigDownC",&leptonSFTrigDownC);
        TChannel_2J_1T_noSyst->SetBranchAddress("leptonSFTrigDownD",&leptonSFTrigDownD);
        TChannel_2J_1T_noSyst->SetBranchAddress("fJetPt",&fJetPt);
        TChannel_2J_1T_noSyst->SetBranchAddress("fJetE",&fJetE);
        TChannel_2J_1T_noSyst->SetBranchAddress("fJetEta",&fJetEta);
        TChannel_2J_1T_noSyst->SetBranchAddress("fJetPhi",&fJetPhi);
        TChannel_2J_1T_noSyst->SetBranchAddress("fJetBtag",&fJetBtag);
        TChannel_2J_1T_noSyst->SetBranchAddress("fJetFlavour",&fJetFlavour);
        TChannel_2J_1T_noSyst->SetBranchAddress("fJetPUID",&fJetPUID);
        TChannel_2J_1T_noSyst->SetBranchAddress("fJetPUWP",&fJetPUWP);
        TChannel_2J_1T_noSyst->SetBranchAddress("fJetBeta",&fJetBeta);
        TChannel_2J_1T_noSyst->SetBranchAddress("fJetDZ",&fJetDZ);
        TChannel_2J_1T_noSyst->SetBranchAddress("fJetRMS",&fJetRMS);
        TChannel_2J_1T_noSyst->SetBranchAddress("bJetBeta",&bJetBeta);
        TChannel_2J_1T_noSyst->SetBranchAddress("bJetDZ",&bJetDZ);
        TChannel_2J_1T_noSyst->SetBranchAddress("bJetRMS",&bJetRMS);
        TChannel_2J_1T_noSyst->SetBranchAddress("bJetPt",&bJetPt);
        TChannel_2J_1T_noSyst->SetBranchAddress("bJetE",&bJetE);
        TChannel_2J_1T_noSyst->SetBranchAddress("bJetEta",&bJetEta);
        TChannel_2J_1T_noSyst->SetBranchAddress("bJetPhi",&bJetPhi);
        TChannel_2J_1T_noSyst->SetBranchAddress("bJetBtag",&bJetBtag);
        TChannel_2J_1T_noSyst->SetBranchAddress("bJetFlavour",&bJetFlavour);
        TChannel_2J_1T_noSyst->SetBranchAddress("bJetPUID",&bJetPUID);
        TChannel_2J_1T_noSyst->SetBranchAddress("bJetPUWP",&bJetPUWP);
        TChannel_2J_1T_noSyst->SetBranchAddress("firstJetPt",&firstJetPt);
        TChannel_2J_1T_noSyst->SetBranchAddress("firstJetEta",&firstJetEta);
        TChannel_2J_1T_noSyst->SetBranchAddress("firstJetPhi",&firstJetPhi);
        TChannel_2J_1T_noSyst->SetBranchAddress("firstJetE",&firstJetE);
        TChannel_2J_1T_noSyst->SetBranchAddress("firstJetBtag",&firstJetBtag);
        TChannel_2J_1T_noSyst->SetBranchAddress("firstJetFlavour",&firstJetFlavour);
        TChannel_2J_1T_noSyst->SetBranchAddress("secondJetPt",&secondJetPt);
        TChannel_2J_1T_noSyst->SetBranchAddress("secondJetEta",&secondJetEta);
        TChannel_2J_1T_noSyst->SetBranchAddress("secondJetPhi",&secondJetPhi);
        TChannel_2J_1T_noSyst->SetBranchAddress("secondJetE",&secondJetE);
        TChannel_2J_1T_noSyst->SetBranchAddress("secondJetBtag",&secondJetBtag);
        TChannel_2J_1T_noSyst->SetBranchAddress("secondJetFlavour",&secondJetFlavour);
        TChannel_2J_1T_noSyst->SetBranchAddress("looseJetPt",&looseJetPt);
        TChannel_2J_1T_noSyst->SetBranchAddress("looseJetEta",&looseJetEta);
        TChannel_2J_1T_noSyst->SetBranchAddress("looseJetPhi",&looseJetPhi);
        TChannel_2J_1T_noSyst->SetBranchAddress("looseJetE",&looseJetE);
        TChannel_2J_1T_noSyst->SetBranchAddress("looseJetBtag",&looseJetBtag);
        TChannel_2J_1T_noSyst->SetBranchAddress("looseJetFlavour",&looseJetFlavour);
        TChannel_2J_1T_noSyst->SetBranchAddress("bJet1Pt",&bJet1Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("bJet1E",&bJet1E);
        TChannel_2J_1T_noSyst->SetBranchAddress("bJet1Eta",&bJet1Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("bJet1Phi",&bJet1Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("bJet1Btag",&bJet1Btag);
        TChannel_2J_1T_noSyst->SetBranchAddress("bJet1Flavour",&bJet1Flavour);
        TChannel_2J_1T_noSyst->SetBranchAddress("bJet2Pt",&bJet2Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("bJet2E",&bJet2E);
        TChannel_2J_1T_noSyst->SetBranchAddress("bJet2Eta",&bJet2Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("bJet2Phi",&bJet2Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("bJet2Btag",&bJet2Btag);
        TChannel_2J_1T_noSyst->SetBranchAddress("bJet2Flavour",&bJet2Flavour);
        TChannel_2J_1T_noSyst->SetBranchAddress("nJLoose",&nJLoose);
        TChannel_2J_1T_noSyst->SetBranchAddress("nJLooseCentral",&nJLooseCentral);
        TChannel_2J_1T_noSyst->SetBranchAddress("nJLooseForward",&nJLooseForward);
        TChannel_2J_1T_noSyst->SetBranchAddress("nJLooseMBTag",&nJLooseMBTag);
        TChannel_2J_1T_noSyst->SetBranchAddress("eventFlavour",&eventFlavour);
        TChannel_2J_1T_noSyst->SetBranchAddress("metPt",&metPt);
        TChannel_2J_1T_noSyst->SetBranchAddress("metPhi",&metPhi);
        TChannel_2J_1T_noSyst->SetBranchAddress("HT",&HT);
        TChannel_2J_1T_noSyst->SetBranchAddress("H",&H);
        TChannel_2J_1T_noSyst->SetBranchAddress("topMass",&topMass);
        TChannel_2J_1T_noSyst->SetBranchAddress("top1Mass",&top1Mass);
        TChannel_2J_1T_noSyst->SetBranchAddress("top2Mass",&top2Mass);
        TChannel_2J_1T_noSyst->SetBranchAddress("topMtw",&topMtw);
        TChannel_2J_1T_noSyst->SetBranchAddress("topPt",&topPt);
        TChannel_2J_1T_noSyst->SetBranchAddress("topPhi",&topPhi);
        TChannel_2J_1T_noSyst->SetBranchAddress("topEta",&topEta);
        TChannel_2J_1T_noSyst->SetBranchAddress("topE",&topE);
        TChannel_2J_1T_noSyst->SetBranchAddress("top1Pt",&top1Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("top1Phi",&top1Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("top1Eta",&top1Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("top1E",&top1E);
        TChannel_2J_1T_noSyst->SetBranchAddress("top2Pt",&top2Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("top2Phi",&top2Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("top2Eta",&top2Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("top2E",&top2E);
        TChannel_2J_1T_noSyst->SetBranchAddress("ID",&ID);
        TChannel_2J_1T_noSyst->SetBranchAddress("MVAID",&MVAID);
        TChannel_2J_1T_noSyst->SetBranchAddress("nVertices",&nVertices);
        TChannel_2J_1T_noSyst->SetBranchAddress("nGoodVertices",&nGoodVertices);
        TChannel_2J_1T_noSyst->SetBranchAddress("totalEnergy",&totalEnergy);
        TChannel_2J_1T_noSyst->SetBranchAddress("totalMomentum",&totalMomentum);
        TChannel_2J_1T_noSyst->SetBranchAddress("lowBTag",&lowBTag);
        TChannel_2J_1T_noSyst->SetBranchAddress("highBTag",&highBTag);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTop_1_Pt",&MCTop_1_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTop_1_Phi",&MCTop_1_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTop_1_Eta",&MCTop_1_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTop_1_E",&MCTop_1_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTop_1_PdgId",&MCTop_1_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTop_1_MotherId",&MCTop_1_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopLepton_1_Pt",&MCTopLepton_1_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopLepton_1_Phi",&MCTopLepton_1_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopLepton_1_Eta",&MCTopLepton_1_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopLepton_1_E",&MCTopLepton_1_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopLepton_1_PdgId",&MCTopLepton_1_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopLepton_1_MotherId",&MCTopLepton_1_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopNeutrino_1_Pt",&MCTopNeutrino_1_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopNeutrino_1_Phi",&MCTopNeutrino_1_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopNeutrino_1_Eta",&MCTopNeutrino_1_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopNeutrino_1_E",&MCTopNeutrino_1_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopNeutrino_1_PdgId",&MCTopNeutrino_1_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopNeutrino_1_MotherId",&MCTopNeutrino_1_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopQuark_1_Pt",&MCTopQuark_1_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopQuark_1_Phi",&MCTopQuark_1_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopQuark_1_Eta",&MCTopQuark_1_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopQuark_1_E",&MCTopQuark_1_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopQuark_1_PdgId",&MCTopQuark_1_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopQuark_1_MotherId",&MCTopQuark_1_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopQuarkBar_1_Pt",&MCTopQuarkBar_1_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopQuarkBar_1_Phi",&MCTopQuarkBar_1_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopQuarkBar_1_Eta",&MCTopQuarkBar_1_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopQuarkBar_1_E",&MCTopQuarkBar_1_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopQuarkBar_1_PdgId",&MCTopQuarkBar_1_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopQuarkBar_1_MotherId",&MCTopQuarkBar_1_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopBQuark_1_Pt",&MCTopBQuark_1_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopBQuark_1_Phi",&MCTopBQuark_1_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopBQuark_1_Eta",&MCTopBQuark_1_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopBQuark_1_E",&MCTopBQuark_1_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopBQuark_1_PdgId",&MCTopBQuark_1_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopBQuark_1_MotherId",&MCTopBQuark_1_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopW_1_Pt",&MCTopW_1_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopW_1_Phi",&MCTopW_1_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopW_1_Eta",&MCTopW_1_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopW_1_E",&MCTopW_1_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopW_1_PdgId",&MCTopW_1_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopW_1_DauOneId",&MCTopW_1_DauOneId);
        TChannel_2J_1T_noSyst->SetBranchAddress("nMCTruthLeptons",&nMCTruthLeptons);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTop_2_Pt",&MCTop_2_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTop_2_Phi",&MCTop_2_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTop_2_Eta",&MCTop_2_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTop_2_E",&MCTop_2_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTop_2_PdgId",&MCTop_2_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTop_2_MotherId",&MCTop_2_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopLepton_2_Pt",&MCTopLepton_2_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopLepton_2_Phi",&MCTopLepton_2_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopLepton_2_Eta",&MCTopLepton_2_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopLepton_2_E",&MCTopLepton_2_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopLepton_2_PdgId",&MCTopLepton_2_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopLepton_2_MotherId",&MCTopLepton_2_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopNeutrino_2_Pt",&MCTopNeutrino_2_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopNeutrino_2_Phi",&MCTopNeutrino_2_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopNeutrino_2_Eta",&MCTopNeutrino_2_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopNeutrino_2_E",&MCTopNeutrino_2_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopNeutrino_2_PdgId",&MCTopNeutrino_2_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopNeutrino_2_MotherId",&MCTopNeutrino_2_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopQuark_2_Pt",&MCTopQuark_2_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopQuark_2_Phi",&MCTopQuark_2_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopQuark_2_Eta",&MCTopQuark_2_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopQuark_2_E",&MCTopQuark_2_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopQuark_2_PdgId",&MCTopQuark_2_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopQuark_2_MotherId",&MCTopQuark_2_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopQuarkBar_2_Pt",&MCTopQuarkBar_2_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopQuarkBar_2_Phi",&MCTopQuarkBar_2_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopQuarkBar_2_Eta",&MCTopQuarkBar_2_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopQuarkBar_2_E",&MCTopQuarkBar_2_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopQuarkBar_2_PdgId",&MCTopQuarkBar_2_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopQuarkBar_2_MotherId",&MCTopQuarkBar_2_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopBQuark_2_Pt",&MCTopBQuark_2_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopBQuark_2_Phi",&MCTopBQuark_2_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopBQuark_2_Eta",&MCTopBQuark_2_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopBQuark_2_E",&MCTopBQuark_2_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopBQuark_2_PdgId",&MCTopBQuark_2_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopBQuark_2_MotherId",&MCTopBQuark_2_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopW_2_Pt",&MCTopW_2_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopW_2_Phi",&MCTopW_2_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopW_2_Eta",&MCTopW_2_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopW_2_E",&MCTopW_2_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopW_2_PdgId",&MCTopW_2_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCTopW_2_DauOneId",&MCTopW_2_DauOneId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_1_Pt",&MCQuark_1_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_1_Phi",&MCQuark_1_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_1_Eta",&MCQuark_1_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_1_E",&MCQuark_1_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_1_PdgId",&MCQuark_1_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_1_MotherId",&MCQuark_1_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_2_Pt",&MCQuark_2_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_2_Phi",&MCQuark_2_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_2_Eta",&MCQuark_2_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_2_E",&MCQuark_2_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_2_PdgId",&MCQuark_2_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_2_MotherId",&MCQuark_2_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_3_Pt",&MCQuark_3_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_3_Phi",&MCQuark_3_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_3_Eta",&MCQuark_3_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_3_E",&MCQuark_3_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_3_PdgId",&MCQuark_3_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_3_MotherId",&MCQuark_3_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_4_Pt",&MCQuark_4_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_4_Phi",&MCQuark_4_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_4_Eta",&MCQuark_4_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_4_E",&MCQuark_4_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_4_PdgId",&MCQuark_4_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_4_MotherId",&MCQuark_4_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_5_Pt",&MCQuark_5_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_5_Phi",&MCQuark_5_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_5_Eta",&MCQuark_5_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_5_E",&MCQuark_5_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_5_PdgId",&MCQuark_5_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_5_MotherId",&MCQuark_5_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_6_Pt",&MCQuark_6_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_6_Phi",&MCQuark_6_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_6_Eta",&MCQuark_6_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_6_E",&MCQuark_6_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_6_PdgId",&MCQuark_6_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_6_MotherId",&MCQuark_6_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_7_Pt",&MCQuark_7_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_7_Phi",&MCQuark_7_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_7_Eta",&MCQuark_7_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_7_E",&MCQuark_7_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_7_PdgId",&MCQuark_7_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_7_MotherId",&MCQuark_7_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_8_Pt",&MCQuark_8_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_8_Phi",&MCQuark_8_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_8_Eta",&MCQuark_8_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_8_E",&MCQuark_8_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_8_PdgId",&MCQuark_8_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_8_MotherId",&MCQuark_8_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_9_Pt",&MCQuark_9_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_9_Phi",&MCQuark_9_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_9_Eta",&MCQuark_9_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_9_E",&MCQuark_9_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_9_PdgId",&MCQuark_9_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_9_MotherId",&MCQuark_9_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_10_Pt",&MCQuark_10_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_10_Phi",&MCQuark_10_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_10_Eta",&MCQuark_10_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_10_E",&MCQuark_10_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_10_PdgId",&MCQuark_10_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_10_MotherId",&MCQuark_10_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_11_Pt",&MCQuark_11_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_11_Phi",&MCQuark_11_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_11_Eta",&MCQuark_11_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_11_E",&MCQuark_11_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_11_PdgId",&MCQuark_11_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_11_MotherId",&MCQuark_11_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_12_Pt",&MCQuark_12_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_12_Phi",&MCQuark_12_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_12_Eta",&MCQuark_12_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_12_E",&MCQuark_12_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_12_PdgId",&MCQuark_12_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCQuark_12_MotherId",&MCQuark_12_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCBQuark_1_Pt",&MCBQuark_1_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCBQuark_1_Phi",&MCBQuark_1_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCBQuark_1_Eta",&MCBQuark_1_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCBQuark_1_E",&MCBQuark_1_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCBQuark_1_PdgId",&MCBQuark_1_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCBQuark_1_MotherId",&MCBQuark_1_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCLepton_1_Pt",&MCLepton_1_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCLepton_1_Phi",&MCLepton_1_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCLepton_1_Eta",&MCLepton_1_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCLepton_1_E",&MCLepton_1_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCLepton_1_PdgId",&MCLepton_1_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCLepton_1_MotherId",&MCLepton_1_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCNeutrino_1_Pt",&MCNeutrino_1_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCNeutrino_1_Phi",&MCNeutrino_1_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCNeutrino_1_Eta",&MCNeutrino_1_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCNeutrino_1_E",&MCNeutrino_1_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCNeutrino_1_PdgId",&MCNeutrino_1_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCNeutrino_1_MotherId",&MCNeutrino_1_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCBQuark_2_Pt",&MCBQuark_2_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCBQuark_2_Phi",&MCBQuark_2_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCBQuark_2_Eta",&MCBQuark_2_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCBQuark_2_E",&MCBQuark_2_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCBQuark_2_PdgId",&MCBQuark_2_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCBQuark_2_MotherId",&MCBQuark_2_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCLepton_2_Pt",&MCLepton_2_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCLepton_2_Phi",&MCLepton_2_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCLepton_2_Eta",&MCLepton_2_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCLepton_2_E",&MCLepton_2_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCLepton_2_PdgId",&MCLepton_2_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCLepton_2_MotherId",&MCLepton_2_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCNeutrino_2_Pt",&MCNeutrino_2_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCNeutrino_2_Phi",&MCNeutrino_2_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCNeutrino_2_Eta",&MCNeutrino_2_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCNeutrino_2_E",&MCNeutrino_2_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCNeutrino_2_PdgId",&MCNeutrino_2_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCNeutrino_2_MotherId",&MCNeutrino_2_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCBQuark_3_Pt",&MCBQuark_3_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCBQuark_3_Phi",&MCBQuark_3_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCBQuark_3_Eta",&MCBQuark_3_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCBQuark_3_E",&MCBQuark_3_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCBQuark_3_PdgId",&MCBQuark_3_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCBQuark_3_MotherId",&MCBQuark_3_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCLepton_3_Pt",&MCLepton_3_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCLepton_3_Phi",&MCLepton_3_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCLepton_3_Eta",&MCLepton_3_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCLepton_3_E",&MCLepton_3_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCLepton_3_PdgId",&MCLepton_3_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCLepton_3_MotherId",&MCLepton_3_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCNeutrino_3_Pt",&MCNeutrino_3_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCNeutrino_3_Phi",&MCNeutrino_3_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCNeutrino_3_Eta",&MCNeutrino_3_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCNeutrino_3_E",&MCNeutrino_3_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCNeutrino_3_PdgId",&MCNeutrino_3_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCNeutrino_3_MotherId",&MCNeutrino_3_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCBQuark_4_Pt",&MCBQuark_4_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCBQuark_4_Phi",&MCBQuark_4_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCBQuark_4_Eta",&MCBQuark_4_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCBQuark_4_E",&MCBQuark_4_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCBQuark_4_PdgId",&MCBQuark_4_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCBQuark_4_MotherId",&MCBQuark_4_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCLepton_4_Pt",&MCLepton_4_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCLepton_4_Phi",&MCLepton_4_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCLepton_4_Eta",&MCLepton_4_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCLepton_4_E",&MCLepton_4_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCLepton_4_PdgId",&MCLepton_4_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCLepton_4_MotherId",&MCLepton_4_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCNeutrino_4_Pt",&MCNeutrino_4_Pt);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCNeutrino_4_Phi",&MCNeutrino_4_Phi);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCNeutrino_4_Eta",&MCNeutrino_4_Eta);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCNeutrino_4_E",&MCNeutrino_4_E);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCNeutrino_4_PdgId",&MCNeutrino_4_PdgId);
        TChannel_2J_1T_noSyst->SetBranchAddress("MCNeutrino_4_MotherId",&MCNeutrino_4_MotherId);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight1",&PDFWeight1);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight2",&PDFWeight2);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight3",&PDFWeight3);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight4",&PDFWeight4);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight5",&PDFWeight5);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight6",&PDFWeight6);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight7",&PDFWeight7);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight8",&PDFWeight8);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight9",&PDFWeight9);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight10",&PDFWeight10);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight11",&PDFWeight11);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight12",&PDFWeight12);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight13",&PDFWeight13);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight14",&PDFWeight14);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight15",&PDFWeight15);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight16",&PDFWeight16);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight17",&PDFWeight17);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight18",&PDFWeight18);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight19",&PDFWeight19);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight20",&PDFWeight20);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight21",&PDFWeight21);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight22",&PDFWeight22);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight23",&PDFWeight23);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight24",&PDFWeight24);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight25",&PDFWeight25);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight26",&PDFWeight26);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight27",&PDFWeight27);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight28",&PDFWeight28);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight29",&PDFWeight29);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight30",&PDFWeight30);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight31",&PDFWeight31);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight32",&PDFWeight32);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight33",&PDFWeight33);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight34",&PDFWeight34);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight35",&PDFWeight35);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight36",&PDFWeight36);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight37",&PDFWeight37);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight38",&PDFWeight38);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight39",&PDFWeight39);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight40",&PDFWeight40);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight41",&PDFWeight41);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight42",&PDFWeight42);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight43",&PDFWeight43);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight44",&PDFWeight44);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight45",&PDFWeight45);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight46",&PDFWeight46);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight47",&PDFWeight47);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight48",&PDFWeight48);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight49",&PDFWeight49);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight50",&PDFWeight50);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight51",&PDFWeight51);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight52",&PDFWeight52);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight_MSTW",&PDFWeight_MSTW);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight_NNPDF21",&PDFWeight_NNPDF21);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight_GJR_FV",&PDFWeight_GJR_FV);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight_GJR_FF",&PDFWeight_GJR_FF);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight_GJR_FDIS",&PDFWeight_GJR_FDIS);
        TChannel_2J_1T_noSyst->SetBranchAddress("PDFWeight_HERAPDF",&PDFWeight_HERAPDF);
        TChannel_2J_1T_noSyst->SetBranchAddress("topPtReweightMCTruthNorm",&topPtReweightMCTruthNorm);
        TChannel_2J_1T_noSyst->SetBranchAddress("topPtReweightNorm",&topPtReweightNorm);
        TChannel_2J_1T_noSyst->SetBranchAddress("topPtReweightMCTruthNormUp",&topPtReweightMCTruthNormUp);
        TChannel_2J_1T_noSyst->SetBranchAddress("topPtReweightNormUp",&topPtReweightNormUp);
        TChannel_2J_1T_noSyst->SetBranchAddress("topPtReweightMCTruthNormDown",&topPtReweightMCTruthNormDown);
        TChannel_2J_1T_noSyst->SetBranchAddress("topPtReweightNormDown",&topPtReweightNormDown);   
   }

   Long64_t nentries = TChannel_2J_1T_noSyst->GetEntries();

   for (Long64_t i=0; i<nentries;i++) {
        TChannel_2J_1T_noSyst->GetEntry(i);
        h_topMass.Fill(topMass);
        h_leptonPt.Fill(leptonPt);
        h_leptonEta.Fill(leptonEta);
        h_leptonPhi.Fill(leptonPhi);
        h_fJetEta.Fill(fJetEta);
        h_bJetEta.Fill(bJetEta);
   }
    cout << "Analyzed " << nentries << " entries\n";
    T.Close();
    E.Write();
    E.Close();
    return 0;
}